# Generated by Django 5.0.3 on 2024-03-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_imuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
