# Generated by Django 5.0.3 on 2024-03-12 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('type_of_service', models.CharField(max_length=100)),
                ('initial_diagnosis', models.TextField()),
                ('repair_option', models.CharField(choices=[('STORE', 'At the Store'), ('RIDER', 'Rider Delivery'), ('HOME', 'Home Service')], max_length=20)),
                ('service_time', models.DateTimeField()),
                ('booking_id', models.CharField(max_length=100)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
