# Generated by Django 5.0.3 on 2024-03-13 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='requester',
            new_name='requester_name',
        ),
    ]
